spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/EventManagementKotlinDB
    username: postgres
    password: ${PG_PASS:qwerty}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    config:
      allEventsTopicKotlin: "allEventsKotlin2"
      cancelledEventsTopicKotlin: "cancelledEventsKotlin"
      groupId: "EventManagementKotlin-group"

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'

    consumer:
      bootstrap-servers: localhost:9092
      group-id: events-group2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    bootstrap-servers: localhost:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: marcinjavadev93@gmail.com
    password: utaq xtbb gggf zorb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    apiKey: 7e546b0a93e0436896c160950242605
    baseUrl: https://api.weatherapi.com/v1/forecast.json